development:
  adapter: postgresql
  encoding: unicode
  database: winejournal_development
  pool: 5
  username: winejournal
  password: winejournal

test:
  adapter: postgresql
  encoding: unicode
  database: winejournal_test
  pool: 5
  username: winejournal
  password: winejournal

production:
  adapter: postgresql
  encoding: unicode
  database: winejournal_production
  pool: 5
  username: winejournal
  password: winejournal
